import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
const inter = Inter({ subsets: ["latin"] });
import Footer from "./_components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#000625] w-full flex justify-center items-center flex-col">
      <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
